### ISSUE TITLE
[1.16.5] Armor stands don't work properly even with vanilla armor

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1536]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {704}

**Operating System :** {Unbuntu 20}

**Logs :** {nope}

**Mod list :** {Command don't work!}

**Plugin list :** {https://haste.mohistmc.com/ononelagad}

**Description of issue :** {Armor details in the video do not fall from the rack. https://youtu.be/NGJeCoKK4Ec}

**Comment by GitJhopa** [comment]
+ armor stand no dropped armor vanilla/mods, all armor no drops... fix pls!

**Comment by XionioXMaster** [comment]
> * armor stand no dropped armor vanilla/mods, all armor no drops... fix pls! i tested build#701

Great, so it’s not just me.
