### ISSUE TITLE
[1.16.5] Tamablefoxes v1.9.1 error on startup

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1538]
Minecraft Version : 1.16.5
Mohist Version : Mohist: 1.16.5-705

Operating System : Unbuntu 20

Concerned mod / plugin : Tamablefoxes v1.9.1

Logs : https://haste.mohistmc.com/emehokijow.properties

Steps to Reproduce :

Install https://www.spigotmc.org/resources/tamable-foxes-1-14-x-1-15-x-1-16-x-1-17-x.69537/ **v1.9.1**

You will notice an error on startup!

**Comment by Shawiizz** [comment]
Why don't use latest version of this plugin ?

**Comment by XionioXMaster** [comment]
> Why don't use latest version of this plugin ?

Because she's for 1.17
