### ISSUE TITLE
[1.16.5] very serious dupe when using Corpse, we need it!

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1544]
Minecraft Version : 1.16.5
Mohist Version : Mohist: 1.16.5-705

Operating System : Unbuntu 20

Concerned mod / plugin : Corpse 1.0.5
Logs : **nope**

Steps to Reproduce :

Install Corpse mod 1.16.5
Video: https://youtu.be/pl92dHcgxn0

CAREFULLY DUPED! I found a creepy error due to which you can cheat shulkers and maybe other things, to do this after death, press U, then go to the things of the last death, hold SHIFT + F and press the right and left mouse buttons on the shulker until open his inventory, everyone will hit him, take 2 shulkers from the corpse!

Since when I use Mohist, the drop can disappear at any time, this is also a bug, I found an alternative to Corpse and it turned out that you can dup there! If the servers do not have this mod, players will lose their belongings due to the strange Mohist bug when things disappear per 2 minutes.

In a single player game, I was unable to implement this bug!

https://github.com/henkelmax/corpse/issues/53

**Comment by joaoespanhol** [comment]
did you test to see if it happens without being mohist, just forge?

**Comment by XionioXMaster** [comment]
> did you test to see if it happens without being mohist, just forge?

I could not repeat it on Forge

**Comment by Romaindu35** [comment]
Can you create this bugs if you don't have any Mods ?

**Comment by XionioXMaster** [comment]
> Can you create this bugs if you don't have any Mods ?

Okay, I'll try now.

**Comment by XionioXMaster** [comment]
> Can you create this bugs if you don't have any Mods ?

I found out a more precise reason, I wasted 2 hours for! The reason is that the CMI plugin, by holding Shift and right clicking on the shulker, you can fool him, I suspect you can bypass hundreds of mods with GUI with it!

**Comment by XionioXMaster** [comment]
Okay....
  # When enabled you will see skull owner name in action bar when right clicking it
  ShowSkullOwner: false
  
  Fix this problem...

I think many will come in handy in the future, God, what a huge config there...

**Comment by XionioXMaster** [comment]
I was wrong nothing was fixed ...
