### ISSUE TITLE
[1.16.5] The server loses the ability to define player mods

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1568]
**Minecraft Version :** 1.16.5

**Mohist Version :** #714

**Operating System :** Unbuntu 20

**Logs :** Client log on join 
https://haste.mohistmc.com/kecaweqiha

Server log
![image](https://user-images.githubusercontent.com/86433158/125743218-88b99bf6-0783-4ffa-9239-226b380f96d9.png)
**Sorry, I lost my .txt log, I will send it back when it happens again**

**Mod list :** ![image](https://user-images.githubusercontent.com/86433158/125742679-ca05d4c7-815c-4220-86b3-a901fd97225d.png)
![image](https://user-images.githubusercontent.com/86433158/125742721-89da311f-1e1b-4c7b-9f33-c802d15b80f9.png)
![image](https://user-images.githubusercontent.com/86433158/125742752-b34c8eba-cf32-4cfb-bf04-660938f6bf86.png)
![image](https://user-images.githubusercontent.com/86433158/125742776-0153ba3e-da84-4659-a3c1-db75e00dbfe8.png)
![image](https://user-images.githubusercontent.com/86433158/125742799-dee86392-22c3-4877-902b-ad499edfdf02.png)
![image](https://user-images.githubusercontent.com/86433158/125742827-249ca9d0-4cf6-4bfe-b246-b122fb2c0355.png)

**Plugin list :** https://haste.mohistmc.com/gogoxelovo

**Description of issue :** Hello, recently the server has begun not to let players into the server, there are absolutely no errors, it happens periodically and I don't know the reason, can I somehow figure it out?

Some users of your discord channel also have a problem.
![Безымянный](https://user-images.githubusercontent.com/86433158/125743114-b320209f-47bd-47a8-8635-3bcbac85639c.png)

**Comment by Mgazul** [comment]
#2009
