### ISSUE TITLE
Finally, fix the drop of items when the armor stand breaks

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1619]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5 735 build

**Operating System :** Unbuntu 20

**Logs :** Nope

**Mod list :** Nope

**Plugin list :** Nope

**Description of issue :** Finally, fix the drop of items when the armor rack breaks https://github.com/MinecraftMist/Mist/commit/7418e0c3268ce237eefadf617ebea518090a42c3

**Comment by Romaindu35** [comment]
Same #1536

**Comment by XionioXMaster** [comment]
> Same #1536

don't work

**Comment by Romaindu35** [comment]
It is just that issue is don't close !
