### ISSUE TITLE
[1.16.5] Failure to comply with the Aquculture 2 vanilla loot table

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1629]
**Minecraft Version :** 1.16.5

**Mohist Version :** 740
**Operating System :** unbuntu 20
**Concerned mod / plugin** : Aquculture 2
**Logs :** Nope
**Steps to Reproduce :**
 1. Install Aquaculture 2 mod
 2. Create a fishing rod as in the screenshot below
 3. Try to fish for the Gift of Neptune. (Luck of the Sea enchantment increases the chance of getting Neptune's Bounty)

![image](https://user-images.githubusercontent.com/86433158/127192611-443164e2-e6ce-412e-8613-c5029df69ad7.png)

**Description of issue :** https://github.com/TeamMetallurgy/Aquaculture/issues/253 I wrote to the author of the mod and he informed me that this is the reason in Mohist

**Comment by XionioXMaster** [comment]
UPD: Gift that contains loot has ???? in description. That is, it will be empty from a creative!
![image](https://user-images.githubusercontent.com/86433158/127884195-374f2332-86f1-41bc-9ed4-38ebb3acd29d.png)

**Comment by Romaindu35** [comment]
Same #1455
