### ISSUE TITLE
[1.16.5] FartherViewDistance plugin, don't work

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1656]
**Minecraft Version :** 1.16.5

**Mohist Version :** 756

**Operating System :** Unbuntu 20

**Concerned mod / plugin** :  Quark mod and FartherViewDistance **1.14~1.16 Use 6.0.4**, ProtocolLib
**Logs :** https://paste.ubuntu.com/p/3qxXrwHKqY/

**Steps to Reproduce :**
 1. Load the plugin and ProtocolLib then login to the server, there will be many errors in the log

**Description of issue :** I put on the server the Quark mod and this plugin https://www.spigotmc.org/resources/fartherviewdistance.84950/

**Comment by Mgazul** [comment]
This error occurs only when installed at the same time as Quark？

**Comment by XionioXMaster** [comment]
> This error occurs only when installed at the same time as Quark？

no, use clear Mohist
