### ISSUE TITLE
[1.16.5] TabList 5.5.5 plugin, don't work

### ISSUE THREAD

**Issue by XionioXMaster** [MohistMC/Mohist#1657]
Minecraft Version : 1.16.5

Mohist Version : 756

Operating System : Unbuntu 20

Concerned mod / plugin : Quark mod and TabList 5.5.5, ProtocolLib
Logs : https://paste.ubuntu.com/p/2MfF2dGwrK/

Steps to Reproduce :

Load the plugin then login to the server, there will be many errors in the log

https://www.spigotmc.org/resources/animated-tab-tablist.46229/?__cf_chl_jschl_tk__=pmd_142b2964b99365c6c6051f85e1e997497c8639a3-1627590371-0-gqNtZGzNAfijcnBszQj6

**Comment by 1798643961** [comment]
Can you give the log？
The log is not available at now...

**Comment by MagnusHJensen** [comment]
I can't reproduce any errors using Mohist 896.
ProtocolLib 4.5.1
TabList 5.6
Quark r2.4-321
AutoRegLib 1.16.49

**Comment by Romaindu35** [comment]
There are no log, and this bug can't be reproduce. If you have always this bug, please open new issue with log
