### ISSUE TITLE
Mohist server Crash 1.18.1 #129 Unknown entity class noobanidus.mods.lootr.entity.LootrChestMinecartEntity

### ISSUE THREAD

**Issue by FabiusHaselnuss** [MohistMC/Mohist#2039]
**Minecraft Version :** 1.18.1

**Mohist Version :** mohist-1.18.1-39.0.66-installer.jar #129

**Operating System :** Ubuntu-18.04.6 LTS

**Logs :** Log: https://controlc.com/5d22a566
                 Crash Report1: https://controlc.com/370902b2
                 Crash Report2: https://controlc.com/1df65be6

**Mod list :** https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3637157

**Plugin list :** LuckPerms, LPC

**Description of issue :** The server crashes right after startup

**Comment by Serega007RU** [comment]
and how was the problem solved? can I link to the commit in which this was fixed?
