### ISSUE TITLE
[1.20.1] 貌似没有完整实现PaperAPI

### ISSUE THREAD

**Issue by Leoparking** [MohistMC/Mohist#3138]
**Minecraft Version :** 1.20.1

**Mohist Version :** 695

**Operating System :** windows 2012R2

**Concerned mod / plugin** : 
因为发现这个插件无法载入，于是问了一下作者，得知FeatherMorph依赖PaperAPI，而错误信息里有一行
`[09:11:31 WARN]: java.lang.NoClassDefFoundError: io/papermc/paper/event/player/PlayerArmSwingEvent`

插件链接👉https://github.com/XiaMoZhiShi/FeatherMorph/issues/13

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. 首先下载上面那个变身插件最新版
 2. 其它都不用管
 3. ...

**Description of issue :** emmmm

**Comment by glowingstone124** [comment]
Mohist本来就没有完整实现PaperApi，仅有部分功能得以实现。
