### ISSUE TITLE
[1.20.1] Model engine & mythic mobs error

### ISSUE THREAD

**Issue by Shisuiicaro** [MohistMC/Mohist#3141]
**Minecraft Version :** 1.20.1

**Mohist Version :** 700

**Operating System :** ubunto

**Concerned mod / plugin** :  Mythic mobs and model engine

**Logs :** [Link(s) of logs and crash reports if you have](https://api.mclo.gs/1/raw/la1lrfM)

**Steps to Reproduce :**
 1. Dowload mohist with a few mods
 2. Dowload mythci mobs/crucible and model engine 4
 3.  Dowload elite creatures kill effect pack and bound it to a weapon
 4. Kill someone and see the log full of erros

**Description of issue :** Give all details about your issue

**Comment by Mgazul** [comment]
Model engine uses a lot of paper APIs, but Mohist does not include them.

**Comment by Shisuiicaro** [comment]
so.. no fix?
