### ISSUE TITLE
java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [MohistMC/Mohist#3272]
**Minecraft Version :** 1.20.1

**Mohist Version :** 749

**Operating System :** win8

**Logs :** 
[logs.txt](https://github.com/user-attachments/files/16451485/logs.txt)

**Mod list :** ![image](https://github.com/user-attachments/assets/7760c2ce-92e6-4fe1-8653-920d291ee068)

**Plugin list :** [14:57:55 INFO]: Plugins (56): PepperMinecart, CreativeTimer
Plugin, FreeMinecraftModels, PlaceholderAPI, HolographicDisp
lays, ConsoleSpamFix, LiteCustomAnnouncer, TrChat, ChineseNi
ckName, ViaVersion, Shift_Menu, ViaBackwards, LuckPerms, Rai
seUp, AnimatedScoreboard, CMILib, LagFixer, RainyRecipe, Sea
sons, LoneLibs, LaggRemover, ProtocolLib, NoSpawnChunks, Lit
eSignIn, MCG, Vault, ViaRewind, ItemCommands, ServerBooster
, TabTPS, SkinsRestorer, ChestCommands, WkKit, dynmap, World
Edit, Essentials, Multiverse-Core, AuthMe, WorldGuard, AuthM
eTitles, BanItem, GSit, CoreProtect, VeinMiner, WorldBorder,
 Kingdoms, Residence, Kingdoms-Addon-Map-Viewers, MTVehicles
, EliteMobs, QuickShop, Interface4, BetterStructures, Space,
 PlugManX (PlugMan), Mohist

**Description of issue :** 不知道是怎么回事，但是日志里在最后关服之前刷了一堆
	at net.minecraft.nbt.TagParser.m_129371_(TagParser.java:132) ~[server-1.20.1-20230612.114412-srg.jar%23232!/:?]

**Comment by Mgazul** [comment]
14个mod(其中12个优化mod)，你不崩谁崩

**Comment by MinecraftEarthVillage** [comment]
> 16个mod(其中14个优化mod)，你不崩谁崩

跟区块有关的全拿掉了，看看接下来怎么样吧🤨
