### ISSUE TITLE
MohistMC always spawns me in survival mode.

### ISSUE THREAD

**Issue by kokofixcomputers** [MohistMC/Mohist#3337]
**Minecraft Version :** 1.20.1 (I would really want this to be fixed in 1.20.1)

**Mohist Version :** 1.20.1-855

**Operating System :** Server is running on Linux. Client doesn't really matter because the vanilla/forge server doesn't have this issue. client is the same.

**Logs :** there are no crash report or logs related to this. all i see it kokofixcomputers set gamemode to creative. kokofixcomputers disconnected and these related.

**Mod list :** a million mods. with the same mods, it still works with forge and does not cause this issue. i cannot find the command getmodlist

**Plugin list :** Multiverse 2 and... thats it.

**Description of issue :** Using mohistmc, it always spawns me in survival mode. in the server.properties, i have set gamemode to creative, and set force-gamemode to true and i was in creative mode when i disconnected last time.

**Comment by AlwaysReadyWBY** [comment]
This has nothing to do with mohist. It's a multiverse problem. You need mv.bypass.gamemode permission to keep the gamemode.

**Comment by kokofixcomputers** [comment]
> This has nothing to do with mohist. It's a multiverse problem. You need mv.bypass.gamemode permission to keep the gamemode.

I mean i though i am the op? i used the /op command on the server and i have access to all the commands!

**Comment by AlwaysReadyWBY** [comment]
> > This has nothing to do with mohist. It's a multiverse problem. You need mv.bypass.gamemode permission to keep the gamemode.
> 
> I mean i though i am the op? i used the /op command on the server and i have access to all the commands!

I'm telling you this because I have the same problem and fixed by adding the permission. Why don't you try it first before you question about it? It won't take much time.

**Comment by kokofixcomputers** [comment]
I found a way to fix it! Thank you for brining that up! Have a nice day!
