### ISSUE TITLE
某玩家无法完全进入游戏，指令登录后断开连接，控制台大量信息

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [MohistMC/Mohist#3433]
**Minecraft Version :** 1.20.1

**Mohist Version :** 737

**Operating System :** 乌班图-22.04-x64

**Logs :** {Link(s) of logs and crash reports if you have}
[截取.txt](https://github.com/user-attachments/files/17868717/default.txt)

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}  （←这个TM提示未知指令）
![image](https://github.com/user-attachments/assets/d3696ae6-58b8-4ae6-b533-947f08a244b5)

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}
![image](https://github.com/user-attachments/assets/35c46e46-0bbc-443c-81ca-66542c758f54)

**Description of issue :** {Give all details about your issue}
玩家方面：可以进入但不登录，
![image](https://github.com/user-attachments/assets/a79ae1bb-b79c-4597-9293-087551dedeec)

输入指令后就会断开连接并出现该提示
![acdf117200d508e624ac8216c3a2ac08](https://github.com/user-attachments/assets/e8c073fa-5f83-401e-930b-8ecf70e1b33c)

**Comment by Mgazul** [comment]
Rmove connectivity mod
